version: '3'
services:
  app:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_USERNAME: app
        DB_PASSWORD: password
        DB_PREFIX: test_
    volumes: 
      - ../InfectedAPI:/srv/infected/InfectedAPI
      - ../InfectedMain:/srv/infected/InfectedMain
      - ../InfectedCrew:/srv/infected/InfectedCrew
      - ../InfectedDeployment:/srv/infected/InfectedDeployment
      - ../InfectedInfo:/srv/infected/InfectedInfo
      - ../InfectedCompo:/srv/infected/InfectedCompo
      - ../InfectedTickets:/srv/infected/InfectedTickets
    image: infected-docker-dev
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DEV_ENVIRONMENT: docker
      PHP_FPM_CLEAR_ENV: "yes"
      DB_PREFIX: test_
      DB_USERNAME: app
      DB_PASSWORD: password
      php.extension: intl.so
    ports:
      - 8080:80
      - 443:443
    entrypoint:
      - /srv/misc/boot
    command:
      - apache2-foreground
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password